CREATE OR REPLACE FILE FORMAT SF_JSON_ECOMDW_FF TYPE=JSON;
--drop table RAW_CUSTOMER_REVIEWS

LS @ex_amz_sf_ecomdw_stg;

ls @ECOM_DW.BRONZE.ex_amz_sf_ecomdw_stg/customer_reviews
SHOW PIPES;
DESC PIPE CUSTOMER_REVIEWS_PIPE;--arn:aws:sqs:eu-north-1:378743674015:sf-snowpipe-AIDAVQLXB2SP66EGGS6F6-rhS3iJj4sJ-VoyVoaHgy1A
select system$pipe_status('CUSTOMER_REVIEWS_PIPE');
SELECT * from TABLE(INFORMATION_SCHEMA.COPY_HISTORY(TABLE_NAME=>'RAW_CUSTOMER_REVIEWS',START_TIME=>DATEADD('hour',-1, CURRENT_TIMESTAMP())));
select * from ECOM_DW.BRONZE.RAW_CUSTOMER_REVIEWS;
--Pipe is invalid because stage EX_AMZ_SF_ECOMDW_STG dropped.
SELECT SYSTEM$PIPE_STATUS('ECOM_DW.BRONZE.CUSTOMER_REVIEWS_PIPE');
--truncate table RAW_CUSTOMER_REVIEWS_BRONZE
CREATE OR REPLACE PIPE CUSTOMER_REVIEWS_PIPE
AUTO_INGEST=TRUE
AS
COPY INTO ECOM_DW.BRONZE.RAW_CUSTOMER_REVIEWS_BRONZE 
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @amz_sf_ecomdw_stg
)
PATTERN = '.*customer_reviews.*\.json$'
FILE_FORMAT = (
    FORMAT_NAME = SF_JSON_ECOMDW_FF
)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE WEB_EVENTS_NESTED_PIPE
AUTO_INGEST=TRUE
AS
COPY INTO ECOM_DW.BRONZE.RAW_WEB_EVENTS_NESTED_BRONZE 
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @amz_sf_ecomdw_stg
)
PATTERN = '.*web_events_nested.*\.json$'
FILE_FORMAT = (
    FORMAT_NAME = SF_JSON_ECOMDW_FF
)
ON_ERROR = 'CONTINUE';

