--Load Dim_Country
CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_DIM_COUNTRY_TASK
WAREHOUSE = ECOM_WH
SCHEDULE = '5 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('ECOM_DW.SILVER.CUSTOMERS_STREAM')
AS
MERGE INTO ECOM_DW.GOLD.DIM_COUNTRY T
USING
(
    SELECT DISTINCT
        COUNTRY_CODE,
        COUNTRY_NAME
    FROM ECOM_DW.SILVER.CUSTOMERS_STREAM
    WHERE METADATA$ACTION = 'INSERT'
) S
ON T.COUNTRY_CODE = S.COUNTRY_CODE
WHEN NOT MATCHED THEN
INSERT
(
    COUNTRY_CODE,
    COUNTRY_NAME
)
VALUES
(
    S.COUNTRY_CODE,
    S.COUNTRY_NAME
);

--Load DIM_STATE
CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_DIM_STATE_TASK
WAREHOUSE = ECOM_WH
AFTER ECOM_DW.GOLD.LOAD_DIM_COUNTRY_TASK
AS
MERGE INTO ECOM_DW.GOLD.DIM_STATE T
USING
(
    SELECT DISTINCT
        STATE_CODE,
        STATE_NAME,
        C.COUNTRY_KEY
    FROM ECOM_DW.SILVER.CUSTOMERS_STREAM S
    JOIN ECOM_DW.GOLD.DIM_COUNTRY C
        ON S.COUNTRY_CODE = C.COUNTRY_CODE
) SRC
ON T.STATE_CODE = SRC.STATE_CODE
WHEN NOT MATCHED THEN
INSERT
(
    STATE_CODE,
    STATE_NAME,
    COUNTRY_KEY
)
VALUES
(
    SRC.STATE_CODE,
    SRC.STATE_NAME,
    SRC.COUNTRY_KEY
);

--load gim_geography
CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_DIM_GEOGRAPHY_TASK
WAREHOUSE = ECOM_WH
AFTER ECOM_DW.GOLD.LOAD_DIM_STATE_TASK
AS
MERGE INTO ECOM_DW.GOLD.DIM_GEOGRAPHY T
USING
(
    SELECT DISTINCT
        CITY,
        POSTAL_CODE,
        ST.STATE_KEY
    FROM ECOM_DW.SILVER.CUSTOMERS_STREAM S
    JOIN ECOM_DW.GOLD.DIM_STATE ST
        ON S.STATE_CODE = ST.STATE_CODE
) SRC
ON T.CITY = SRC.CITY
AND T.POSTAL_CODE = SRC.POSTAL_CODE
WHEN NOT MATCHED THEN
INSERT
(
    CITY,
    POSTAL_CODE,
    STATE_KEY
)
VALUES
(
    SRC.CITY,
    SRC.POSTAL_CODE,
    SRC.STATE_KEY
);

--Load dim_customer SCD Type 2
CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_DIM_CUSTOMER_TASK
WAREHOUSE = ECOM_WH
AFTER ECOM_DW.GOLD.LOAD_DIM_GEOGRAPHY_TASK
AS
MERGE INTO ECOM_DW.GOLD.DIM_CUSTOMER T
USING
(
    SELECT
        CUSTOMER_ID,
        CUSTOMER_ID AS CUSTOMER_NK,
        FIRST_NAME,
        LAST_NAME,
        CONCAT(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME,
        EMAIL,
        PHONE,
        GENDER,
        DATE_OF_BIRTH,
        CUSTOMER_STATUS,
        G.GEOGRAPHY_KEY,
        CURRENT_TIMESTAMP() AS EFFECTIVE_FROM
    FROM ECOM_DW.SILVER.CUSTOMERS_STREAM S
    LEFT JOIN ECOM_DW.GOLD.DIM_GEOGRAPHY G
        ON S.CITY = G.CITY
        AND S.POSTAL_CODE = G.POSTAL_CODE
) SRC
ON T.CUSTOMER_ID = SRC.CUSTOMER_ID
AND T.IS_CURRENT = TRUE
WHEN MATCHED AND
(
    T.EMAIL <> SRC.EMAIL
    OR T.PHONE <> SRC.PHONE
    OR T.CUSTOMER_STATUS <> SRC.CUSTOMER_STATUS
    OR T.GEOGRAPHY_KEY <> SRC.GEOGRAPHY_KEY
)
THEN UPDATE SET
T.EFFECTIVE_TO = CURRENT_TIMESTAMP(),
    T.IS_CURRENT = FALSE
WHEN NOT MATCHED THEN
INSERT
(
    CUSTOMER_ID,
    CUSTOMER_NK,
    FIRST_NAME,
    LAST_NAME,
    FULL_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    CUSTOMER_STATUS,
    GEOGRAPHY_KEY,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT
)
VALUES
(
    SRC.CUSTOMER_ID,
    SRC.CUSTOMER_NK,
    SRC.FIRST_NAME,
    SRC.LAST_NAME,
    SRC.FULL_NAME,
    SRC.EMAIL,
    SRC.PHONE,
    SRC.GENDER,
    SRC.DATE_OF_BIRTH,
    SRC.CUSTOMER_STATUS,
    SRC.GEOGRAPHY_KEY,
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
);

--Load Dim_Product
CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_DIM_PRODUCT_TASK
WAREHOUSE = ECOM_WH
WHEN SYSTEM$STREAM_HAS_DATA('ECOM_DW.SILVER.PRODUCTS_STREAM')
AS
MERGE INTO ECOM_DW.GOLD.DIM_PRODUCT T
USING
(
    SELECT
        PRODUCT_ID,
        PRODUCT_ID AS PRODUCT_NK,
        SKU,
        PRODUCT_NAME,
        BRAND,
        UNIT_COST,
        UNIT_PRICE,
        IS_ACTIVE
    FROM ECOM_DW.SILVER.PRODUCTS_STREAM
) SRC
ON T.PRODUCT_ID = SRC.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
    T.PRODUCT_NAME = SRC.PRODUCT_NAME,
    T.BRAND = SRC.BRAND,
    T.UNIT_COST = SRC.UNIT_COST,
    T.UNIT_PRICE = SRC.UNIT_PRICE,
    T.IS_ACTIVE = SRC.IS_ACTIVE
WHEN NOT MATCHED THEN
INSERT
(
 PRODUCT_ID,
    PRODUCT_NK,
    SKU,
    PRODUCT_NAME,
    BRAND,
    UNIT_COST,
    UNIT_PRICE,
    IS_ACTIVE
)
VALUES
(
    SRC.PRODUCT_ID,
    SRC.PRODUCT_NK,
    SRC.SKU,
    SRC.PRODUCT_NAME,
    SRC.BRAND,
    SRC.UNIT_COST,
    SRC.UNIT_PRICE,
    SRC.IS_ACTIVE
);

--Load Dim_Channel
CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_DIM_CHANNEL_TASK
WAREHOUSE = ECOM_WH
WHEN SYSTEM$STREAM_HAS_DATA('ECOM_DW.SILVER.CHANNELS_STREAM')
AS
MERGE INTO ECOM_DW.GOLD.DIM_CHANNEL T
USING
(
    SELECT DISTINCT
        CHANNEL_CODE,
        CHANNEL_NAME,
        CHANNEL_TYPE
    FROM ECOM_DW.SILVER.CHANNELS_STREAM
) SRC
ON T.CHANNEL_CODE = SRC.CHANNEL_CODE
WHEN MATCHED THEN UPDATE SET
    T.CHANNEL_NAME = SRC.CHANNEL_NAME,
    T.CHANNEL_TYPE = SRC.CHANNEL_TYPE
WHEN NOT MATCHED THEN
INSERT
(
    CHANNEL_CODE,
    CHANNEL_NAME,
    CHANNEL_TYPE
)
VALUES
(
    SRC.CHANNEL_CODE,
    SRC.CHANNEL_NAME,
    SRC.CHANNEL_TYPE
);

--Load Dim Promotion
CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_DIM_PROMOTION_TASK
WAREHOUSE = ECOM_WH
WHEN SYSTEM$STREAM_HAS_DATA('ECOM_DW.SILVER.PROMOTIONS_STREAM')
AS
MERGE INTO ECOM_DW.GOLD.DIM_PROMOTION T
USING
(
    SELECT *
    FROM ECOM_DW.SILVER.PROMOTIONS_STREAM
) SRC
ON T.PROMO_CODE = SRC.PROMO_CODE
WHEN MATCHED THEN UPDATE SET
    T.PROMO_NAME = SRC.PROMO_NAME,
    T.DISCOUNT_TYPE = SRC.DISCOUNT_TYPE,
    T.DISCOUNT_VALUE = SRC.DISCOUNT_VALUE,
    T.START_DATE = SRC.START_DATE,
    T.END_DATE = SRC.END_DATE,
    T.IS_ACTIVE = SRC.IS_ACTIVE
WHEN NOT MATCHED THEN
INSERT
(
    PROMO_CODE,
    PROMO_NAME,
    DISCOUNT_TYPE,
    DISCOUNT_VALUE,
    START_DATE,
    END_DATE,
    IS_ACTIVE
)
VALUES
(
    SRC.PROMO_CODE,
    SRC.PROMO_NAME,
    SRC.DISCOUNT_TYPE,
    SRC.DISCOUNT_VALUE,
    SRC.START_DATE,
    SRC.END_DATE,
    SRC.IS_ACTIVE
);

--Load Fact Sales
CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_FACT_SALES_TASK
WAREHOUSE = ECOM_WH
AFTER ECOM_DW.GOLD.LOAD_DIM_CUSTOMER_TASK,
      ECOM_DW.GOLD.LOAD_DIM_PRODUCT_TASK,
      ECOM_DW.GOLD.LOAD_DIM_CHANNEL_TASK,
      ECOM_DW.GOLD.LOAD_DIM_PROMOTION_TASK
AS
INSERT INTO ECOM_DW.GOLD.FACT_SALES
(
    ORDER_ID,
    ORDER_LINE_NK,
    ORDER_DATE_KEY,
    CUSTOMER_KEY,
    PRODUCT_KEY,
    CHANNEL_KEY,
    PROMOTION_KEY,
    QUANTITY,
    UNIT_PRICE,
    UNIT_COST,
    GROSS_AMOUNT,
    DISCOUNT_AMOUNT,
    TAX_AMOUNT,
    NET_AMOUNT
)
SELECT
    O.ORDER_ID,
    O.ORDER_LINE_ID,
    TO_NUMBER(TO_CHAR(TO_DATE(O.ORDER_DATE),'YYYYMMDD')),
    DC.CUSTOMER_KEY,
    DP.PRODUCT_KEY,
    DCH.CHANNEL_KEY,
    PR.PROMOTION_KEY,
    O.QUANTITY::NUMBER(18,2),
    O.UNIT_PRICE::NUMBER(18,2),
    DP.UNIT_COST,
    O.GROSS_AMOUNT::NUMBER(18,2),
    O.DISCOUNT_AMOUNT::NUMBER(18,2),
    O.TAX_AMOUNT::NUMBER(18,2),
    O.NET_AMOUNT::NUMBER(18,2)
FROM ECOM_DW.SILVER.ORDERS_STREAM O
LEFT JOIN ECOM_DW.GOLD.DIM_CUSTOMER DC
    ON O.CUSTOMER_ID = DC.CUSTOMER_ID
    AND DC.IS_CURRENT = TRUE
LEFT JOIN ECOM_DW.GOLD.DIM_PRODUCT DP
    ON O.PRODUCT_ID = DP.PRODUCT_ID
LEFT JOIN ECOM_DW.GOLD.DIM_CHANNEL DCH
    ON O.CHANNEL_CODE = DCH.CHANNEL_CODE
LEFT JOIN ECOM_DW.GOLD.DIM_PROMOTION PR
    ON O.PROMO_CODE = PR.PROMO_CODE;

    --Load FACT_SHIPMENT
    CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_FACT_SHIPMENT_TASK
WAREHOUSE = ECOM_WH
AFTER ECOM_DW.GOLD.LOAD_DIM_CUSTOMER_TASK,
      ECOM_DW.GOLD.LOAD_DIM_PRODUCT_TASK
AS
INSERT INTO ECOM_DW.GOLD.FACT_SHIPMENT
(
    SHIPMENT_ID,
    ORDER_ID,
    SHIPMENT_DATE_KEY,
    CUSTOMER_KEY,
    PRODUCT_KEY,
    SHIPPED_QTY,
    SHIPPING_COST,
    DELIVERY_DAYS
)
SELECT
    SHIPMENT_ID,
    ORDER_ID,
    TO_NUMBER(TO_CHAR(SHIPMENT_DATE,'YYYYMMDD')),
    DC.CUSTOMER_KEY,
    DP.PRODUCT_KEY,
    SHIPPED_QTY,
    SHIPPING_COST,
    DELIVERY_DAYS
FROM ECOM_DW.SILVER.SHIPMENTS_STREAM S
LEFT JOIN ECOM_DW.GOLD.DIM_CUSTOMER DC
    ON S.CUSTOMER_ID = DC.CUSTOMER_ID
    AND DC.IS_CURRENT = TRUE
LEFT JOIN ECOM_DW.GOLD.DIM_PRODUCT DP
    ON S.PRODUCT_ID = DP.PRODUCT_ID;



    CREATE OR REPLACE STREAM ECOM_DW.SILVER.INVENTORY_STREAM
ON TABLE ECOM_DW.SILVER.INVENTORY_SILVER;



CREATE OR REPLACE TABLE ECOM_DW.GOLD.ETL_ERROR_LOG
(
    ERROR_ID            NUMBER AUTOINCREMENT,
    PIPELINE_NAME       STRING,
    SOURCE_TABLE        STRING,
    ERROR_MESSAGE       STRING,
    ERROR_RECORD        VARIANT,
    ERROR_TIMESTAMP     TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE VIEW ECOM_DW.GOLD.VW_INVENTORY_VALIDATION
AS
SELECT
    SNAPSHOT_DATE,
    PRODUCT_ID,

    TRY_TO_NUMBER(ON_HAND_QTY)       AS ON_HAND_QTY,
    TRY_TO_NUMBER(RESERVED_QTY)      AS RESERVED_QTY,
    TRY_TO_NUMBER(AVAILABLE_QTY)     AS AVAILABLE_QTY,
    TRY_TO_NUMBER(UNIT_COST)         AS UNIT_COST,
    TRY_TO_NUMBER(INVENTORY_VALUE)   AS INVENTORY_VALUE,

    SOURCE_SYSTEM,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP

FROM ECOM_DW.SILVER.INVENTORY_SILVER;

INSERT INTO ECOM_DW.GOLD.ETL_ERROR_LOG
(
    PIPELINE_NAME,
    SOURCE_TABLE,
    ERROR_MESSAGE,
    ERROR_RECORD
)
SELECT
    'FACT_INVENTORY_LOAD',
    'INVENTORY_SILVER',
    'Invalid numeric conversion',
    OBJECT_CONSTRUCT(*)

FROM ECOM_DW.SILVER.INVENTORY_SILVER
WHERE
    TRY_TO_NUMBER(ON_HAND_QTY) IS NULL
    OR TRY_TO_NUMBER(UNIT_COST) IS NULL;--not working

    --. FACT_INVENTORY Load Task
    CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_FACT_INVENTORY_TASK
WAREHOUSE = ECOM_WH

AFTER ECOM_DW.GOLD.LOAD_DIM_PRODUCT_TASK

WHEN SYSTEM$STREAM_HAS_DATA('ECOM_DW.SILVER.INVENTORY_STREAM')

AS

INSERT INTO ECOM_DW.GOLD.FACT_INVENTORY
(
    SNAPSHOT_DATE_KEY,
    PRODUCT_KEY,
    ON_HAND_QTY,
    RESERVED_QTY,
    AVAILABLE_QTY,
    UNIT_COST,
    INVENTORY_VALUE
)

SELECT

    TO_NUMBER(
        TO_CHAR(
            TO_DATE(SNAPSHOT_DATE),
            'YYYYMMDD'
        )
    ) AS SNAPSHOT_DATE_KEY,

    DP.PRODUCT_KEY,

    TRY_TO_NUMBER(I.ON_HAND_QTY,18,2),

    TRY_TO_NUMBER(I.RESERVED_QTY,18,2),

    TRY_TO_NUMBER(I.AVAILABLE_QTY,18,2),

    TRY_TO_NUMBER(I.UNIT_COST,18,2),

    TRY_TO_NUMBER(I.INVENTORY_VALUE,18,2)

FROM ECOM_DW.SILVER.INVENTORY_STREAM I

INNER JOIN ECOM_DW.GOLD.DIM_PRODUCT DP
    ON I.PRODUCT_ID = DP.PRODUCT_ID

WHERE
    TRY_TO_NUMBER(I.ON_HAND_QTY) IS NOT NULL
    AND TRY_TO_NUMBER(I.UNIT_COST) IS NOT NULL;

    CREATE OR REPLACE VIEW ECOM_DW.GOLD.VW_INVENTORY_DEDUP
AS

SELECT *
FROM
(
    SELECT
        *,
        ROW_NUMBER() OVER
        (
            PARTITION BY SNAPSHOT_DATE, PRODUCT_ID
            ORDER BY UPDATED_TIMESTAMP DESC
        ) AS RN

    FROM ECOM_DW.SILVER.INVENTORY_SILVER
)
WHERE RN = 1;

CREATE OR REPLACE TABLE ECOM_DW.GOLD.AGG_INVENTORY_DAILY
(
    SNAPSHOT_DATE_KEY     NUMBER,
    TOTAL_ON_HAND_QTY     NUMBER(18,2),
    TOTAL_RESERVED_QTY    NUMBER(18,2),
    TOTAL_AVAILABLE_QTY   NUMBER(18,2),
    TOTAL_INVENTORY_VALUE NUMBER(18,2)
);

CREATE OR REPLACE TASK ECOM_DW.GOLD.LOAD_AGG_INVENTORY_TASK
WAREHOUSE = ECOM_WH

AFTER ECOM_DW.GOLD.LOAD_FACT_INVENTORY_TASK

AS

MERGE INTO ECOM_DW.GOLD.AGG_INVENTORY_DAILY T

USING
(
    SELECT
        SNAPSHOT_DATE_KEY,

        SUM(ON_HAND_QTY)       AS TOTAL_ON_HAND_QTY,

        SUM(RESERVED_QTY)      AS TOTAL_RESERVED_QTY,

        SUM(AVAILABLE_QTY)     AS TOTAL_AVAILABLE_QTY,

        SUM(INVENTORY_VALUE)   AS TOTAL_INVENTORY_VALUE

    FROM ECOM_DW.GOLD.FACT_INVENTORY

    GROUP BY SNAPSHOT_DATE_KEY

) S

ON T.SNAPSHOT_DATE_KEY = S.SNAPSHOT_DATE_KEY

WHEN MATCHED THEN UPDATE SET

    T.TOTAL_ON_HAND_QTY = S.TOTAL_ON_HAND_QTY,
    T.TOTAL_RESERVED_QTY = S.TOTAL_RESERVED_QTY,
    T.TOTAL_AVAILABLE_QTY = S.TOTAL_AVAILABLE_QTY,
    T.TOTAL_INVENTORY_VALUE = S.TOTAL_INVENTORY_VALUE

WHEN NOT MATCHED THEN

INSERT
(
    SNAPSHOT_DATE_KEY,
    TOTAL_ON_HAND_QTY,
    TOTAL_RESERVED_QTY,
    TOTAL_AVAILABLE_QTY,
    TOTAL_INVENTORY_VALUE
)

VALUES
(
    S.SNAPSHOT_DATE_KEY,
    S.TOTAL_ON_HAND_QTY,
    S.TOTAL_RESERVED_QTY,
    S.TOTAL_AVAILABLE_QTY,
    S.TOTAL_INVENTORY_VALUE
);

CREATE MATERIALIZED VIEW ECOM_DW.GOLD.MV_PRODUCT_INVENTORY
AS

SELECT

    D.YEAR_NUMBER,
    D.MONTH_NUMBER,

    P.PRODUCT_NAME,
    P.BRAND,

    SUM(F.ON_HAND_QTY) AS TOTAL_STOCK,

    SUM(F.INVENTORY_VALUE) AS TOTAL_VALUE

FROM ECOM_DW.GOLD.FACT_INVENTORY F

JOIN ECOM_DW.GOLD.DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY

JOIN ECOM_DW.GOLD.DIM_DATE D
    ON F.SNAPSHOT_DATE_KEY = D.DATE_KEY

GROUP BY
    D.YEAR_NUMBER,
    D.MONTH_NUMBER,
    P.PRODUCT_NAME,
    P.BRAND;

ALTER TABLE ECOM_DW.GOLD.FACT_INVENTORY
CLUSTER BY
(
    SNAPSHOT_DATE_KEY,
    PRODUCT_KEY
);

CREATE OR REPLACE VIEW ECOM_DW.GOLD.VW_INVENTORY_HEALTH
AS

SELECT

    P.PRODUCT_NAME,

    SUM(F.ON_HAND_QTY) AS STOCK_QTY,

    SUM(F.RESERVED_QTY) AS RESERVED_QTY,

    SUM(F.AVAILABLE_QTY) AS AVAILABLE_QTY,

    CASE
        WHEN SUM(F.AVAILABLE_QTY) < 10
            THEN 'LOW STOCK'

        WHEN SUM(F.AVAILABLE_QTY) = 0
            THEN 'OUT OF STOCK'

        ELSE 'HEALTHY'
    END AS STOCK_STATUS

FROM ECOM_DW.GOLD.FACT_INVENTORY F

JOIN ECOM_DW.GOLD.DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY

GROUP BY P.PRODUCT_NAME;

ALTER TASK ECOM_DW.GOLD.LOAD_FACT_INVENTORY_TASK RESUME;

ALTER TASK ECOM_DW.GOLD.LOAD_AGG_INVENTORY_TASK RESUME;

ALTER TABLE ECOM_DW.GOLD.FACT_INVENTORY
ADD SEARCH OPTIMIZATION;