
# PART 1 — ROW LEVEL SECURITY (RLS)

RLS in Snowflake is implemented using:

* **Row Access Policies**
* (Optionally) Secure Views

---

# 1. CUSTOMER COUNTRY-BASED RLS


Restrict users so they only see customers from their region (example: Germany users see only Germany data).

---

## Step 1: Create Row Access Policy

```sql
CREATE OR REPLACE ROW ACCESS POLICY ECOM_DW.GOLD.RAP_CUSTOMER_COUNTRY
AS (COUNTRY_NAME STRING)
RETURNS BOOLEAN ->

CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN TRUE

    WHEN CURRENT_ROLE() = 'ECOM_ANALYST_ROLE'
         AND COUNTRY_NAME = 'Germany'
    THEN TRUE

    WHEN CURRENT_ROLE() = 'ECOM_BI_ROLE'
    THEN TRUE

    ELSE FALSE
END;
```

---

## Step 2: Apply to DIM_CUSTOMER

```sql
ALTER TABLE ECOM_DW.GOLD.DIM_CUSTOMER
ADD ROW ACCESS POLICY ECOM_DW.GOLD.RAP_CUSTOMER_COUNTRY
ON (COUNTRY_NAME);
```

---

# 2. FACT SALES ROW LEVEL SECURITY

## Goal

Filter FACT_SALES via CUSTOMER → COUNTRY mapping.

---

## Create Policy

```sql
CREATE OR REPLACE ROW ACCESS POLICY ECOM_DW.GOLD.RAP_FACT_SALES
AS (CUSTOMER_KEY NUMBER)
RETURNS BOOLEAN ->

EXISTS
(
    SELECT 1
    FROM ECOM_DW.GOLD.DIM_CUSTOMER C
    WHERE C.CUSTOMER_KEY = CUSTOMER_KEY
    AND (
        CURRENT_ROLE() IN ('ACCOUNTADMIN','SYSADMIN')
        OR C.COUNTRY_NAME = 'Germany'
        OR CURRENT_ROLE() = 'ECOM_BI_ROLE'
    )
);
```

---

##  Apply Policy

```sql
ALTER TABLE ECOM_DW.GOLD.FACT_SALES
ADD ROW ACCESS POLICY ECOM_DW.GOLD.RAP_FACT_SALES
ON (CUSTOMER_KEY);
```

---

# 3. CUSTOMER REVIEW RLS (Sensitive Data)


Restrict review visibility (especially negative feedback)

---

##  Policy

```sql
CREATE OR REPLACE ROW ACCESS POLICY ECOM_DW.GOLD.RAP_CUSTOMER_REVIEW
AS (SENTIMENT_LABEL STRING)
RETURNS BOOLEAN ->

CASE
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN TRUE

    WHEN CURRENT_ROLE() = 'ECOM_ANALYST_ROLE'
         AND SENTIMENT_LABEL != 'NEGATIVE'
    THEN TRUE

    WHEN CURRENT_ROLE() = 'ECOM_BI_ROLE' THEN TRUE

    ELSE FALSE
END;
```

---

## Step 2: Apply

```sql
ALTER TABLE ECOM_DW.GOLD.FACT_CUSTOMER_REVIEW
ADD ROW ACCESS POLICY ECOM_DW.GOLD.RAP_CUSTOMER_REVIEW
ON (SENTIMENT_LABEL);
```

---

# 4. PRODUCT-BASED RLS (Optional Advanced)

Example: restrict inactive products

```sql
CREATE OR REPLACE ROW ACCESS POLICY ECOM_DW.GOLD.RAP_PRODUCT
AS (IS_ACTIVE BOOLEAN)
RETURNS BOOLEAN ->

CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','SYSADMIN') THEN TRUE
    WHEN IS_ACTIVE = TRUE THEN TRUE
    ELSE FALSE
END;
```

---



```sql
ALTER TABLE ECOM_DW.GOLD.DIM_PRODUCT
ADD ROW ACCESS POLICY ECOM_DW.GOLD.RAP_PRODUCT
ON (IS_ACTIVE);
```

---

# — SECURE DATA SHARING

Snowflake supports secure sharing via **Secure Data Shares (zero-copy sharing)**.

---

# 1. CREATE SHARE OBJECT

## Create Share

```sql
CREATE OR REPLACE SHARE ECOM_ANALYTICS_SHARE;
```

---

# 2. GRANT DATABASE ACCESS

```sql
GRANT USAGE ON DATABASE ECOM_DW TO SHARE ECOM_ANALYTICS_SHARE;

GRANT USAGE ON SCHEMA ECOM_DW.GOLD TO SHARE ECOM_ANALYTICS_SHARE;
```

---

# 3. GRANT OBJECTS TO SHARE

## FACT TABLES

```sql
GRANT SELECT ON TABLE ECOM_DW.GOLD.FACT_SALES TO SHARE ECOM_ANALYTICS_SHARE;

GRANT SELECT ON TABLE ECOM_DW.GOLD.FACT_SHIPMENT TO SHARE ECOM_ANALYTICS_SHARE;

GRANT SELECT ON TABLE ECOM_DW.GOLD.FACT_INVENTORY TO SHARE ECOM_ANALYTICS_SHARE;

GRANT SELECT ON TABLE ECOM_DW.GOLD.FACT_CUSTOMER_REVIEW TO SHARE ECOM_ANALYTICS_SHARE;
```

---

## DIMENSIONS

```sql
GRANT SELECT ON TABLE ECOM_DW.GOLD.DIM_CUSTOMER TO SHARE ECOM_ANALYTICS_SHARE;

GRANT SELECT ON TABLE ECOM_DW.GOLD.DIM_PRODUCT TO SHARE ECOM_ANALYTICS_SHARE;

GRANT SELECT ON TABLE ECOM_DW.GOLD.DIM_DATE TO SHARE ECOM_ANALYTICS_SHARE;

GRANT SELECT ON TABLE ECOM_DW.GOLD.DIM_GEOGRAPHY TO SHARE ECOM_ANALYTICS_SHARE;
```

---

## AGGREGATES

```sql
GRANT SELECT ON TABLE ECOM_DW.GOLD.AGG_DAILY_SALES TO SHARE ECOM_ANALYTICS_SHARE;
```

---

# 4. ADD CONSUMER ACCOUNT


```sql
ALTER SHARE ECOM_ANALYTICS_SHARE
ADD ACCOUNTS = ('<consumer_account_locator>');
```


```sql
ALTER SHARE ECOM_ANALYTICS_SHARE
ADD ACCOUNTS = ('ABC12345');
```

---

# 5. OPTIONAL: CREATE SECURE VIEWS FOR SHARING

Instead of raw tables 

## Secure Sales View

```sql
CREATE OR REPLACE SECURE VIEW ECOM_DW.GOLD.VW_SHARED_SALES
AS
SELECT
    F.ORDER_DATE_KEY,
    F.CUSTOMER_KEY,
    F.PRODUCT_KEY,
    F.NET_AMOUNT
FROM ECOM_DW.GOLD.FACT_SALES F;
```

---

## Share Secure View

```sql
GRANT SELECT ON VIEW ECOM_DW.GOLD.VW_SHARED_SALES TO SHARE ECOM_ANALYTICS_SHARE;
```

---

# 6. CONSUMER SIDE 



```sql
CREATE DATABASE ECOM_SHARED_DB
FROM SHARE PROVIDER_ACCOUNT.ECOM_ANALYTICS_SHARE;
```

```sql
SELECT * FROM ECOM_SHARED_DB.GOLD.FACT_SALES;



# SECURITY LAYER SUMMARY

| Layer             | Method                               |
| ----------------- | ------------------------------------ |
| Row Filtering     | Row Access Policy                    |
| Column Protection | Masking Policy                       |
| External Sharing  | Secure Share                         |
| BI Access         | Secure Views                         |
| AI Access         | Controlled role + Cortex permissions |

---
