--Customer Stream
CREATE OR REPLACE STREAM ECOM_DW.SILVER.CUSTOMERS_STREAM
ON TABLE ECOM_DW.SILVER.CUSTOMERS_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.PRODUCTS_STREAM
ON TABLE ECOM_DW.SILVER.PRODUCTS_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.ORDERS_STREAM
ON TABLE ECOM_DW.SILVER.ORDERS_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.PROMOTIONS_STREAM
ON TABLE ECOM_DW.SILVER.PROMOTIONS_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.CHANNELS_STREAM
ON TABLE ECOM_DW.SILVER.CHANNELS_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.INVENTORY_STREAM
ON TABLE ECOM_DW.SILVER.INVENTORY_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.SHIPMENTS_STREAM
ON TABLE ECOM_DW.SILVER.SHIPMENTS_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.SHIPPING_METHODS_STREAM
ON TABLE ECOM_DW.SILVER.SHIPPING_METHODS_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.CUSTOMER_REVIEWS_STREAM
ON TABLE ECOM_DW.SILVER.CUSTOMER_REVIEWS_SILVER;

CREATE OR REPLACE STREAM ECOM_DW.SILVER.WEB_EVENTS_STREAM
ON TABLE ECOM_DW.SILVER.WEB_EVENTS_SILVER;

--Email Masking
CREATE OR REPLACE MASKING POLICY EMAIL_MASK AS
(val STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('SYSADMIN','ACCOUNTADMIN') THEN val
    ELSE REGEXP_REPLACE(val,'.+@','*****@')
END;

--phone masking
CREATE OR REPLACE MASKING POLICY PHONE_MASK AS
(val STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('SYSADMIN','ACCOUNTADMIN') THEN val
    ELSE CONCAT('XXXXXX', RIGHT(val,4))
END;
--customer name masking
CREATE OR REPLACE MASKING POLICY NAME_MASK AS
(val STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('SYSADMIN','ACCOUNTADMIN') THEN val
    ELSE CONCAT(LEFT(val,1),'*****')
END;

--Apply Masking Policies

ALTER TABLE ECOM_DW.GOLD.DIM_CUSTOMER
MODIFY COLUMN EMAIL
SET MASKING POLICY EMAIL_MASK;

ALTER TABLE ECOM_DW.GOLD.DIM_CUSTOMER
MODIFY COLUMN PHONE
SET MASKING POLICY PHONE_MASK;

ALTER TABLE ECOM_DW.GOLD.DIM_CUSTOMER
MODIFY COLUMN FIRST_NAME
SET MASKING POLICY NAME_MASK;

ALTER TABLE ECOM_DW.GOLD.DIM_CUSTOMER
MODIFY COLUMN LAST_NAME
SET MASKING POLICY NAME_MASK;

